### ISSUE TITLE
UploadedFileInfo  for it to emit UploadFolder/FilePath

### ISSUE THREAD

**Issue by zoinkydoink** [DataJuggler/BlazorFileUpload#2]
When a file is uploaded, UploadedFileInfo  should have a property that states the path the file was uploaded (combine UploadFolder with FileName).

Basically this line `Path.Combine(UploadFolder, uploadedFileInfo.FullName)` that is in FileUpload.Razor

**Comment by DataJuggler** [comment]
Sounds reasonable to me. I was thinking of building an Image Gallery Sample this weekend, so I will try and add this property.

Thanks for the suggestion.

**Comment by DataJuggler** [comment]
I updated the Nuget package to version 1.1.0 (not preview) and included this property.

I haven't had a chance to test it as my sample project is taking longer than I had to work on it today.

If you get a chance can you test it? I will check in the code with the latest here soon.

Thanks

**Comment by zoinkydoink** [comment]
latest version seems to provide the full path of where it was uploaded so this is perfect

**Comment by DataJuggler** [comment]
Great. I will close this issue. It is on my to do list to test it, but I am building an image gallery sample and haven't had a chance yet.

Thanks
