### ISSUE TITLE
Upload same file does not work second time

### ISSUE THREAD

**Issue by zoinkydoink** [DataJuggler/BlazorFileUpload#3]
It seems that when you upload a file successfully and then do it again a second time, does not work second time.
Here is my configuration

```
        <FileUpload CustomSuccessMessage="Your file uploaded successfully." OnChange="OnFileUploaded"
                    PartialGuidLength="10" MaxFileSize="4194304" UploadFolder="@settings.UploadFolderPath"
                    FilterByExtension="true" AllowedExtensions=".jpg;.png;.pdf"
                    CustomExtensionMessage="Only .pdf, .jpg and .png files are allowed." AppendPartialGuid="true"
                    FileTooLargeMessage="The file uploaded must be 4 megabytes or smaller.">
```

**Comment by DataJuggler** [comment]
I will take a look at this in this morning. 

Not sure if this will help, but I read a similar issue on BlazorInputFile project:

https://github.com/SteveSandersonMS/BlazorInputFile/issues/2

I will look for a more elegant solution, or write a Reset method if I can figure it out, but maybe setting a variable like the workaround offered will work?

Corby

**Comment by DataJuggler** [comment]
Are you still having a problem with this? If you get the latest version of the code and / or Nuget package, there are now some properties for:

1. ShowResetButton - Default = true
After an upload, this button will show to clear the UI.

2. Reset Button Text - You can change Reset to New or Change, etc:
ResetButtonText="Change"

3. ResetButtonCSS - You can add your own style to the Reset button.

I have been able to add the same files many times. 

Let me know if this still an issue for you please, else I would like to close this issue as I cannot duplicate the problem.

Thanks

**Comment by DataJuggler** [comment]
I am closing this issue. This has been fixed.
