### ISSUE TITLE
Uploading in EditForm resets the page

### ISSUE THREAD

**Issue by QadiymStewart** [DataJuggler/BlazorFileUpload#8]
Some how when the component is used within an edit form it submits the form when upload finishes. Any fix for this?

**Comment by DataJuggler** [comment]
I am building an image gallery sample and I have not experienced this issue. I will post the new sample as soon as I can I got distracted this weekend on a progress bar sample.

I will post the database for this project and setup instructions as soon as I can, but if you run this sample, click the SIgn Up button you can see how I did it maybe it will help you:

https://github.com/DataJuggler/BlazorImageGallery

If your code is something you can share I can take a look at it when I get time (my weekend free time just ran out). I do not have much to go by from your description of the issue.

Sorry it isn't working for you.

Corby

**Comment by QadiymStewart** [comment]
Alright it seems to be working fine in a clean project. Must be something in the current project I'm working on looks like StateHasChanged is getting triggered somewhere.

**Comment by QadiymStewart** [comment]
Found the bug. It was the live reload package I was using.  Got to ignore that upload folder so it doesn't trigger. Thanks for the fast response tho. 👍
